config/routes.rb
Rails.application.routes.draw do
  resources :pratos do
    resources :comentarios
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => redirect('/pratos')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :prato
  validates :autor, :presence => true
  validates :corpo, :presence => true
end

app/models/prato.rb
class Prato < ApplicationRecord
    has_attached_file :image, :styles => { :medium => "300x300>"}
    has_many :comentarios, dependent: :destroy
    validates :nome, :presence => true
    validates :descricao, :presence => true
    validates :image, :presence => true
    validates :nome_usuario, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
    def create
      @prato = Prato.find(params[:prato_id])
      @comentario = @prato.comentarios.create(com_params)
      redirect_to prato_path(@prato)
    end
    
    def destroy
      @prato = Prato.find(params[:prato_id])
      @comentario = @prato.comentarios.find(params[:id])
      @comentario.destroy
      redirect_to prato_path(@prato)
    end
    
    def com_params
      params.require(:comentario).permit(:autor, :corpo)
    end
  end

app/controllers/pratos_controller.rb
class PratosController < ApplicationController
  before_action :set_prato, only: [:show, :edit, :update, :destroy]

  # GET /pratos
  # GET /pratos.json
  def index
    @pratos = Prato.all
  end

  # GET /pratos/1
  # GET /pratos/1.json
  def show
  end

  # GET /pratos/new
  def new
    @prato = Prato.new
  end

  # GET /pratos/1/edit
  def edit
  end

  # POST /pratos
  # POST /pratos.json
  def create
    @prato = Prato.new(prato_params)

    respond_to do |format|
      if @prato.save
        format.html { redirect_to @prato, notice: 'Prato was successfully created.' }
        format.json { render :show, status: :created, location: @prato }
      else
        format.html { render :new }
        format.json { render json: @prato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pratos/1
  # PATCH/PUT /pratos/1.json
  def update
    respond_to do |format|
      if @prato.update(prato_params)
        format.html { redirect_to @prato, notice: 'Prato was successfully updated.' }
        format.json { render :show, status: :ok, location: @prato }
      else
        format.html { render :edit }
        format.json { render json: @prato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pratos/1
  # DELETE /pratos/1.json
  def destroy
    @prato.destroy
    respond_to do |format|
      format.html { redirect_to pratos_url, notice: 'Prato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prato
      @prato = Prato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prato_params
      params.require(:prato).permit(:nome, :descricao, :image, :nome_usuario)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/pratos_helper.rb
module PratosHelper
end

app/views/comentarios/_form.html.erb
<%= form_with(model: comentario, local: true) do |form| %>
  <% if comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
        <% comentario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= form.label :autor %>
      <%= form.text_field :autor %>
    </div>

    <div class="field">
      <%= form.label :corpo %>
      <%= form.text_field :corpo %>
    </div>

    <div class="field">
      <%= form.label :prato_id %>
      <%= form.text_field :prato_id %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Corpo</th>
      <th>Prato</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.autor %></td>
        <td><%= comentario.corpo %></td>
        <td><%= comentario.prato_id %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @comentario.autor %>
</p>

<p>
  <strong>Corpo:</strong>
  <%= @comentario.corpo %>
</p>

<p>
  <strong>Prato:</strong>
  <%= @comentario.prato_id %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ep3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://railsgirls.com/assets/bootstrap.css">
    <link href="https://fonts.googleapis.com/css?family=Bangers&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <div class= "cabecalho">
            <a class="brand" href="/"><h1>Festival Gastrômico FGA</h1></a>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
</html>

app/views/pratos/_form.html.erb
<link href="https://fonts.googleapis.com/css?family=Concert+One&display=swap" rel="stylesheet">

<%= form_with(model: prato, local: true, :html => { :multipart => true }) do |form| %>
  <% if prato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prato.errors.count, "error") %> prohibited this prato from being saved:</h2>

      <ul>
        <% prato.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="formulario">
    <div class="field">
      <div class = "label">
        <%= form.label :Nome %>
      </div>

      <div class = "text_area">
        <%= form.text_field :nome %>
      </div>
    </div>

    <div class="field">
      <div class = "label">
        <%= form.label :Descrição %>
      </div>

      <div class = "text_area">
        <%= form.text_area :descricao %>
      </div>
    </div>

    <div class="field">
      <div class = "label">
        <%= form.label :Imagem %>
      </div>
      <div class = "text_area">
        <%= form.file_field :image %>
      </div>
    </div>

    <div class="field">
      <div class = "label">
        <%= form.label :Equipe %>
      </div>
      <div class = "text_area">
        <%= form.text_field :nome_usuario %>
      </div>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/pratos/edit.html.erb
<link href="https://fonts.googleapis.com/css?family=Concert+One&display=swap" rel="stylesheet">
<h3>Editar prato</h3>

<%= render 'form', prato: @prato %>

<div class = "links_edit">
    <%= link_to 'Voltar', @prato %> |
    <%= link_to 'Inicio', pratos_path %>
</div>

app/views/pratos/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Concert+One&display=swap" rel="stylesheet">
<p id="notice"><%= notice %></p>

<div class=tpratos>
  <h2>Pratos:</h2>
  <hr class="style-seven" />
</div>

<table cellspacing="10">
  <tbody>
    <% @pratos.each do |prato| %>
        <td>
          <%= image_tag(prato.image.url(:medium)) %><br />
          <div class = nome_prato>
            <%= prato.nome %><br />
          </div>
          <div class = link_ver_prato>
            <%= link_to 'Ver', prato %><br />
          </div>
        </td>
    <% end %>
  </tbody>
</table>

<hr class="style-seven" />

<br>

<div class = "link_cadastrar_prato">
  <%= link_to 'Cadastrar Prato', new_prato_path %>
</div>

app/views/pratos/new.html.erb
<h2>Cadastrar Prato</h2>

<%= render 'form', prato: @prato %>
<div class="links_edit">
    <%= link_to 'Voltar', pratos_path %>
</div>

app/views/pratos/show.html.erb
<p id="notice"><%= notice %></p>
<link href="https://fonts.googleapis.com/css?family=Concert+One&display=swap" rel="stylesheet">

<div class="left">
  <div class ="show_imagem">
    <p>
      <%= image_tag(@prato.image.url(:medium)) %>
    </p>
  </div>

  <div class ="show_prato">
    <p>
      <%= @prato.nome %>
    </p>
  </div>

  <div class ="show_descricao_equipe">
    <p>
      <u>Descrição</u>:
      <%= @prato.descricao %>
    </p>

    <p>
      <u>Equipe</u>:
      <%= @prato.nome_usuario %>
    </p>
  </div>

  <div class = "links_show">
    <%= link_to 'Exluir', @prato, method: :delete, data: { confirm: 'Você tem certeza?' } %> |
    <%= link_to 'Editar', edit_prato_path(@prato) %> |
    <%= link_to 'Voltar', pratos_path %><br />
  </div>
</div>

<div class="right">
  <div class = "comentarios">
    <h3>Comentários</h3>
    <% @prato.comentarios.each do |comentario| %>
      <p>
        <b>Autor:</b>
        <%= comentario.autor %>
      </p>
    
      <p>
        <b>Comentario:</b><br />
        <%= comentario.corpo %>
      </p>
      
      <p>
        <%= link_to 'Apagar Comentário', [comentario.prato, comentario], :method => :delete, data: { confirm: 'Você tem certeza?' } %>
      </p>

    <hr class="style-seven" />
    <% end %>
    
    <h3>Adicione um comentário:</h3>

    <%= form_for([@prato, @prato.comentarios.build]) do |f| %>
      <div class="formulario">
        
        <div class="field">
            <div class = "labelc">
              <%= f.label :Autor %><br />
            </div>
          <%= f.text_field :autor %>
        </div>

        <div class="field">
          <div class = "labelc">
            <%= f.label :Comentário %><br />
          </div>
          <%= f.text_area :corpo %>
        </div>
        
        <div class="actions">
          <%= f.submit %>
        </div>
      </div>
  <% end %>
  
  <br />
  </div>
</div>